---
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+[-a-z0-9]*$/

jobs:
  fast_finish: true

  include:
    - &PHP

      os: linux

      dist: xenial

      cache:
        directories:
          - "$HOME/.composer/cache"

      language: php

      php: 7.2

      env: PREFER_LOWEST=--prefer-lowest

      before_install:
        - phpenv config-rm xdebug.ini

      install:
        - composer update --no-progress --no-suggest --prefer-dist $PREFER_LOWEST --optimize-autoloader

      script:
        - ./vendor/bin/phpcs --standard=PSR2 -n src
        - ./vendor/bin/phpunit --colors=always

    - <<: *PHP

      php: 7.3

      env: PREFER_LOWEST=

    - <<: *PHP

      php: 7.4

      env: PREFER_LOWEST=

    - &CodeCoverage

      stage: Code Coverage

      os: linux

      dist: xenial

      cache:
        directories:
          - "$HOME/.composer/cache"

      language: php

      php: 7.2

      install:
        - composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader

      script:
        - ./vendor/bin/phpunit --coverage-clover=coverage.xml

      after_success:
        - bash <(curl -s https://codecov.io/bash)
